name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Set up Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run buildprod
        run: ./scripts/buildprod.sh

      - name: Migrate DB
        run: ./scripts/migrateup.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'submit build to gcloud repo'
        run : gcloud builds submit --tag us-central1-docker.pkg.dev/calm-energy-481619-d7/notely-ar-repo/notely:latest .

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-central1-docker.pkg.dev/calm-energy-481619-d7/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project calm-energy-481619-d7 --max-instances=4

  # gcloud:
  #   name: Deploy
  #   runs-on: ubuntu-latest

  #   steps:
  #   - id: 'auth'
  #     uses: 'google-github-actions/auth@v2'
  #     with:
  #       credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

  #   - name: 'Set up Cloud SDK'
  #     uses: 'google-github-actions/setup-gcloud@v3'

  #   - name: 'Use gcloud CLI'
  #     run: 'gcloud info'

  #   - name: 'submit build to gcloud repo'
  #     run : gcloud builds submit --tag us-central1-docker.pkg.dev/calm-energy-481619-d7/notely-ar-repo/notely:latest .